version: '3.8'

services:
  # Main FastAPI application
  farmer-ai:
    build: ..
    ports:
      - "8000:8000"
    environment:
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - PARAM_MODEL_PATH=/app/models/param-1-2.9b-instruct
      - DEVICE=cpu
      - VAKYANSH_STT_URL=http://stt-service:8001/stt
      - VAKYANSH_TTS_URL=http://tts-service:8002/tts
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=False
    volumes:
      - ../models:/app/models
    depends_on:
      - stt-service
      - tts-service
    restart: unless-stopped

  # STT Service (Vakyansh)
  stt-service:
    image: vakyansh/stt:latest
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
    restart: unless-stopped

  # TTS Service (Vakyansh)
  tts-service:
    image: vakyansh/tts:latest
    ports:
      - "8002:8002"
    environment:
      - PORT=8002
    restart: unless-stopped

  # Redis for conversation context (optional)
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - farmer-ai
    restart: unless-stopped

volumes:
  redis_data: 